# Generated by Django 4.0.5 on 2022-06-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('network', models.CharField(max_length=128)),
                ('network_id', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=42)),
            ],
        ),
    ]
